CSCfi/pouta-ansible-cluster

roles/persistent_lvm_storage/tasks/main.yml

- works also if no swap lv or data lv has been created

activate all lvs in the vg_data

---

playbooks/hortonworks/cluster_vars.yaml.example-complex
playbooks/hortonworks/cluster_vars.yaml.example-io-flavor
playbooks/hortonworks/provision.yml

- added automatic master floating ip assignment (it was accidentally removed during refactoring)
- also added an option to assign a predetermined floating ip
- updated cluster_var.yaml examples
Thanks for Aleksander Agafonov for bug report

Add the auto_ip functionality back

---

playbooks/hortonworks/README.md
playbooks/hortonworks/cluster_vars.yaml.example-complex
playbooks/hortonworks/cluster_vars.yaml.example-io-flavor
tasks/vm_group_provision.yml

* made server groups optional
* added a variable to cluster_vars.yaml for assigning a group of VMs to a certain server group
* updated the README
* fixes #33

server_group changes to make PAC work with OpenStack Liberty

---

roles/docker_host/tasks/main.yml
roles/lvm_storage/tasks/configure_filesystem.yml
roles/lvm_storage/tasks/configure_swap.yml
roles/lvm_storage/tasks/configure_volume.yml

* include condition for swap config needs to be based on a fact. reason is currently unknown
* suppressed changes for scan and activate vg operations
* lowercase names for swap tasks

swap config bug fix and cleanup

---

tasks/vm_group_deprovision.yml
tasks/vm_group_provision.yml

- aliases for VMs are managed in .ssh/config for easier access
- created when provisioning, removed when deprovisioning
- StrictHostKeyChecking is disabled for managed hosts

ssh config aliases

---

playbooks/hortonworks/README.md
playbooks/hortonworks/provision.yml
roles/ambari_server/handlers/main.yml
roles/ambari_server/tasks/main.yml
roles/base/tasks/main.yml
roles/cluster_common/templates/etc/sysconfig/iptables.j2
roles/cluster_master/tasks/main.yml
roles/hortonworks_common/handlers/main.yml
roles/hortonworks_common/tasks/main.yml
roles/nfs_server/handlers/main.yml
roles/nfs_server/tasks/main.yml
tasks/create_tmuxinator_config.yml

- support for Ansible 2.2
- relative paths for creating inventory do not work anymore, switched to using HOME
- iptables installed and activated by default
- $HOME/.ssh/config is populated with provisioned VMs, providing aliases
- hortonworks README updated

general provisioning enhancements

---

playbooks/openshift/example_cluster_vars.yaml
playbooks/openshift/templates/inventory.multimaster.j2
playbooks/openshift/templates/inventory.single_master.j2

Take metrics image version from specified release, image tag or
explicitly set oso_metrics_tag. The installer defaults to 'latest',
which can lead to problems later when incompatible changes are
introduced.

support setting explicit metrics version in inventory

---

roles/base/tasks/main.yml
roles/cluster_master/tasks/main.yml
tasks/vm_group_volume_attach.yml
tasks/vm_group_volume_deprovision.yml
tasks/vm_group_volume_provision.yml

Ansible 2.3 spits warnings about jinja2 template variable syntax in
when statements. See
http://docs.ansible.com/ansible/playbooks_conditionals.html#the-when-statement
http://stackoverflow.com/questions/42673045/ansible-when-statements-should-not-include-jinja2-templating-delimiters

remove jinja2 templating from when statements

---

playbooks/openshift/templates/inventory.multimaster.j2
playbooks/openshift/templates/inventory.single_master.j2

Heapster needs to be run on infra-nodes to have access to node API.
The new openshift_metrics -role in installer supports setting
nodeSelectors, so we set them in the inventory avoiding a manual step
after installation.

set nodeSelector for metrics pods

---

playbooks/openshift/templates/inventory.multimaster.j2

Remove a an extraneous attribute and a invalid variable reference for nfs server in multimaster inventory template. This looks like it was introduced when openshift_hostname -attributes in inventory were added to provide human readable names for nodes. NFS server does not need it, because it does not act as an OpenShift node.

remove extra openshift_hostname variable in inventory for nfs

---

playbooks/openshift/templates/inventory.multimaster.j2
playbooks/openshift/templates/inventory.single_master.j2

Previously the ansible_ssh_user and ansible_become variables were not
being set for NFS servers. This caused Ansible to be unable to connect
to these servers as the proper username was not being used. For other
servers the username is set in the OSEv3 group, but the NFS servers do
not belong to this group.
Set ansible_ssh_user to cloud-user and ansible_become to true in the NFS
server inventory group.

Set ansible_{ssh_user,become} for NFS servers

---

playbooks/openshift/provision.yml

The "Generate inventory, tmuxinator config and ssh config" task assumes
that the directory {{ ansible_env.HOME }}/{{ cluster_name }} already
exists. This directory should be created before running the task to
make sure inventory creation does not fail. Create this inventory.

Make sure dir exists for autogenerated inventory

---

playbooks/openshift/README.md
playbooks/openshift/example_cluster_vars.yaml

- updated image tag to 1.4.1 in example_cluster_vars.yaml
- added a reference to bastion host instructions
- updated the branch reference for openshift-ansible-tourunen
- updated instructions for creating cluster_vars.yaml
- fixed references to local checkout of OpenShift installer
- changed setup_lvm_nfs playbook to generic post_install playbook
- dropped using root shell for actions after installation
- added deprovisioning example
- added project_external_ips to the list of variables to configure

update OpenShift installation instructions

---

roles/ambari_server/tasks/main.yml
roles/docker_host/tasks/main.yml

service module state 'running' is now deprecated and should be
replaced with 'started'
http://docs.ansible.com/ansible/service_module.html#options

service module running state to started

---

playbooks/openshift/clouds.yaml

The clouds.yaml config file that is used to configure the
openstack.py dynamic inventory script is not needed after all, as we've
modified the script defaults to be more sane. The only thing that was
being set by cloud.yaml was one boolean value, basically. Remove
clouds.yaml.

Remove clouds.yaml

---

playbooks/openshift/README.md
playbooks/openshift/files/openshift-heat-stack.yml
playbooks/openshift/heat_deprovision.yml
playbooks/openshift/heat_provision.yml

Modify the Heat template for the OpenShift cluster so that a dedicated
router and network is always created. Use the defaults when creating
these dedicated resources via os_stack.

Always create dedicated net+router for OpenShift

---

playbooks/openshift/files/openshift-heat-stack.yml

To differentiate multiple deployments, add a new metadata variable
"stack" to all OpenShift VMs. This can be used by a dynamic inventory
script to filter out VMs that don't belong into the current deployments.

Add stack metadata tag to all OpenShift VMs

---

playbooks/openshift/files/openshift-heat-stack-minimal.yml
playbooks/openshift/files/openshift-heat-stack.yml
playbooks/openshift/heat_provision.yml

It looks like new routers in cPouta take a long time to start working.
It is thus better to use an existing router instead and connect that to
the cluster network create in the Heat stack. The name of this existing
router is provided as a parameter to the stack. Also change the default
CIDR of the cluster network to a /24 from a /16, because with an
existing router one has to avoid collissions with other networks
connected to the same router.
Improve SSH connectivity checking. The setup module is not ideal for
connection checking. It is better to use wait_for. First wait for the
bastion separately, then make sure the bastion has nmap-ncat installed
and finally ensure SSH connectivity to all cluster hosts.

Better reliability for OpenShift Heat provisioning

---

playbooks/openshift/ansible.cfg

Configure callback_whitelist in ansible.cfg so that it includes the
profile_tasks callback function that gives additional timing information
during playbook runs.

Use profile_tasks callback

---

playbooks/openshift/post_install.yml
playbooks/openshift/templates/cinder-storageclass.yaml.j2
playbooks/openshift/templates/project-request.yaml

Add post-install tasks and a Jinja2 template for adding a Cinder storage
class in OpenShift.
Make it possible to configure a default storage quota for new projects
in OpenShift using a ResourceQuota object. The quota is based on a
variable and a default is provided for overriding the value. Set a
default of 500Gi to start with.

Configuration for Cinder storage class

---

playbooks/openshift/heat_deprovision.yml
playbooks/openshift/heat_provision.yml
playbooks/openshift/pre_install.yml

We don't really need to gather facts for e.g. OpenStack API calls, so
let's not do it. It can cause unnecessary issues.
Also, make sure to use connection: local whenever running plays on the
localhost.

Set gather_facts: no for many localhost plays

---

playbooks/openshift/environment_context.yml
playbooks/openshift/heat_deprovision.yml
playbooks/openshift/heat_provision.yml
playbooks/openshift/pre_install.yml

When running tasks such as OpenStack API calls on the localhost, the
right context may not have been available previously. Add a
localhost_context.yml file with two tasks for getting context from the
correct group under group_vars. Include this file for those plays that
need it.

Get context for current environment when needed

---

playbooks/openshift/heat_deprovision.yml
playbooks/openshift/heat_provision.yml
playbooks/openshift/post_install.yml

Moving registry PVC allocation after Cinder dynamic storage has been
initialized, making registry use Cinder instead of NFS. This will remove
the hard requirement of having NFS PVs configured for a simple
deployment.

registry now uses cinder persistent storage

---

playbooks/openshift/post_install.yml

Fixes #84
Fix a bug where environment variables for oso-default-www are not
set in the deployment config and the rendered template does not
have proper links. The bug must have slipped through when the
deployment method was converted from a dc template to running
'oc new-app'.

set the environment variables in oso-default-www deployment config

---

playbooks/openshift/heat_provision.yml

To prevent from accidentally causing a replace of resources by stack
update, a condition has been added to os_stack tasks to run them only
if the stack does not exist yet. A more elegant solution is needed in
the future.

provision stack only once

---

tasks/vm_group_provision.yml

This patch changes scheduler hint assignment mechanism so that
if no server group is assigned, scheduler hints is an empty
dictionary. Previously the group -key was just set to '', but
this does not work anymore.
Fixes #87

allow empty server groups with OpenStack Newton

---

container-src/pac-deployer/requirements.txt

Metrics deployment needs passlib on the control host. Adding
passlib 1.7.1 to requirements.

add passlib to requirements

---

playbooks/openshift/pre_install.yml

Prior to this LVM was not configured on etcd hosts and docker storage
was left on defaults. Docker was installed by openshift, unlike
the rest of the hosts.

configure lvm and docker on etcd servers

---

CREATE_BASTION_HOST.md
tasks/vm_group_provision.yml

CentOS 7 image is now (correctly) called CentOS-7 in cPouta. Update the defaults to match this.

update Centos-7 image reference to new cPouta convention
